# Generated by Django 4.0 on 2022-02-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_pedido_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='imagem',
            field=models.FileField(blank=True, upload_to='app/static/public/cardapio/'),
        ),
    ]
