# Generated by Django 4.0 on 2022-02-18 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_prato_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prato',
            old_name='imagem',
            new_name='image',
        ),
    ]
