# Generated by Django 4.0 on 2022-02-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_prato_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='image',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
