# Generated by Django 4.0 on 2022-03-07 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_descricao_prato_desc_rename_nome_prato_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='valor',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='prato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.prato', verbose_name='Prato'),
        ),
    ]
