# Generated by Django 4.0 on 2022-03-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_created_at_pedido_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='disponibilidade',
            field=models.BooleanField(default=True),
        ),
    ]
