# Generated by Django 4.0 on 2022-03-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_gerencial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gerencial',
            options={'verbose_name_plural': 'Gerencial'},
        ),
        migrations.AddField(
            model_name='gerencial',
            name='main_image',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
