# Generated by Django 4.0 on 2022-03-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_gerencial_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerencial',
            name='logo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gerencial',
            name='main_image',
            field=models.TextField(blank=True),
        ),
    ]
