# Generated by Django 4.0 on 2022-03-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_gerencial_logo_alter_gerencial_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerencial',
            name='link_instagram',
            field=models.TextField(blank=True, verbose_name='Link Instagram'),
        ),
        migrations.AddField(
            model_name='gerencial',
            name='link_whatsapp',
            field=models.TextField(blank=True, verbose_name='Link WhatsApp'),
        ),
        migrations.AddField(
            model_name='gerencial',
            name='nome_estabelecimento',
            field=models.CharField(default=1, max_length=12, verbose_name='Nome do Estabelecimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gerencial',
            name='logo',
            field=models.TextField(blank=True, verbose_name='Icone Logo'),
        ),
        migrations.AlterField(
            model_name='gerencial',
            name='main_image',
            field=models.TextField(blank=True, verbose_name='Imagem Principal'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='desc',
            field=models.CharField(max_length=60, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='disponibilidade',
            field=models.BooleanField(default=True, verbose_name='Disponível'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='image',
            field=models.TextField(blank=True, max_length=255, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='ingredients',
            field=models.CharField(max_length=100, verbose_name='Ingredientes'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='value',
            field=models.FloatField(verbose_name='Valor'),
        ),
    ]
