# Generated by Django 4.0 on 2022-03-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_gerencial_link_instagram_gerencial_link_whatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='ingredients',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ingredientes'),
        ),
    ]
