# Generated by Django 4.0 on 2022-03-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_prato_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerencial',
            name='link_whatsapp',
            field=models.CharField(blank=True, max_length=13, verbose_name='Link WhatsApp'),
        ),
    ]
