# Generated by Django 4.0 on 2022-03-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_gerencial_link_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerencial',
            name='nome_estabelecimento',
            field=models.CharField(max_length=16, verbose_name='Nome do Estabelecimento'),
        ),
    ]
