# Generated by Django 4.0 on 2022-03-28 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_link_whatsapp_gerencial_num_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('desc', models.CharField(max_length=160, verbose_name='Descrição')),
                ('ingredients', models.CharField(blank=True, max_length=100, verbose_name='Ingredientes')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('disponibilidade', models.BooleanField(default=True, verbose_name='Disponível')),
                ('image', models.TextField(blank=True, max_length=255, verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='prato',
        ),
        migrations.AlterField(
            model_name='gerencial',
            name='link_instagram',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link Instagram'),
        ),
        migrations.DeleteModel(
            name='Prato',
        ),
        migrations.AddField(
            model_name='pedido',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.produto', verbose_name='Produto'),
            preserve_default=False,
        ),
    ]
