# Generated by Django 4.0 on 2022-03-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_produto_remove_pedido_prato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerencial',
            name='service',
            field=models.CharField(choices=[(1, 'Food Service'), (2, 'Varejo Service')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gerencial',
            name='num_whatsapp',
            field=models.CharField(blank=True, max_length=13, verbose_name='Nº WhatsApp'),
        ),
    ]
