# Generated by Django 4.0 on 2022-03-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_gerencial_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerencial',
            name='service',
            field=models.IntegerField(choices=[(1, 'Food Service'), (2, 'Varejo Service')], max_length=2, verbose_name='Tipo de serviço'),
        ),
    ]
